{"name": "Проверка возвращаемой ошибки при неправильном пароле", "status": "passed", "start": 1699269590993, "stop": 1699269591307, "uuid": "4b8eac4c-c78c-40bc-b396-4a5a07515622", "historyId": "60c993ae204684f2639f8908d3e86d98", "testCaseId": "60c993ae204684f2639f8908d3e86d98", "fullName": "tests.test_courier_login.TestCourierLogin#test_auth_with_incorrect_password_error", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier_login"}, {"name": "subSuite", "value": "TestCourierLogin"}, {"name": "host", "value": "MacBook-Air-Arsenij.local"}, {"name": "thread", "value": "26665-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier_login"}]}